INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Emagrecimento', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Ganho de massa magra', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Manutenção', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Melhora da performance atlética', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Aumento da energia', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Redução de colesterol', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Controle de diabetes', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Aumento da imunidade', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Saúde intestinal', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Alimentação saudável para gestantes', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Controle de alergias ou intolerâncias alimentares', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO public.tipo_meta (descricao, created_at, updated_at) VALUES ('Pré e pós-operatório', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );