INSERT INTO public.meta (paciente_id, tipo_meta_id, data_inicio, data_fim, status_meta_id, created_at, updated_at)
VALUES 
    (1, 1, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 1, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 2, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 2, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 3, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 3, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (7, 1, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 2, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (9, 3, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10, 1, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '31 days', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
